"use client"

import React, { createContext, useContext, useEffect, useState, ReactNode } from 'react'

type Lang = 'de' | 'en'

type LangContextType = {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string, fallback?: string) => string
}

const LanguageContext = createContext<LangContextType | undefined>(undefined)

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  de: {
    app_title: 'Börsensaufen 🍻',
    // categories
    cat_saefte: 'Säfte & Schorlen',
    cat_bier: 'Bier & Biermischgetränke',
    cat_non_alc: 'Softdrinks',
    cat_wine: 'Wein',
    cat_mocktails: 'Mocktails (alkoholfrei)',
    cat_cocktails: 'Cocktails',
    home_title: 'Servus,',
    home_subtitle: 'Scanne den Tisch-QR-Code, um am Börsensaufen teilzunehmen!',
      finished_per_hour: 'Fertig pro Stunde',
      disclaimer_title: 'Wichtige Hinweise',
      disclaimer_1: 'Keine Rückerstattungen möglich',
      disclaimer_2: 'Aus Sicherheits- und Verwaltungsgründen kannst du maximal das 3-fache deiner Gruppengröße an Getränken pro Bestellung aufgeben',
      disclaimer_3: 'Alle Bestellungen werden auf einmal zum Tisch geliefert, Getränke können nicht verzögert werden',
      disclaimer_4: 'Essen ist nicht im Börsenhandel enthalten',
      disclaimer_5: 'Das Bestellen von Getränken zu regulären Preisen ist heute nicht möglich',
      disclaimer_6: 'Das Eröffnen einer Gruppe ist nur gegen Vorlage eines Studentenausweises (o.Ä.) möglich',
      disclaimer_7: 'Jedes Produkt hat eine versteckte Kapazität, danach ist es für die Nacht ausverkauft',
      disclaimer_8: 'Es wird zufällige Events geben',
      disclaimer_9: 'Bestellungen müssen innerhalb von 1 Minute abgeschlossen werden, um den Preis zu behalten',
    nav_home: 'Startseite',
    nav_drinks: 'Getränke',
    nav_dashboard: 'Dashboard',
    nav_my_party: 'Meine Gruppe',
    login: 'Anmelden',
    logout: 'Abmelden',
    notfound_title: '404 – Seite nicht gefunden',
    notfound_sub: 'Die gesuchte Seite konnte nicht gefunden werden.',
    go_back_home: 'Zurück zur Startseite',
    cookie_prompt_title: 'Sprache & Cookies',
    cookie_prompt_text: 'Wähle eine Sprache. Wir speichern außerdem notwendige Cookies (z.B. Session). Du kannst weitere Cookies später anpassen.',
    accept: 'Akzeptieren',
  choose_de: 'Deutsch',
  choose_en: 'English',
  choose_language: 'Sprache wählen',
    // additional
    loading: 'Lädt...',
    no_products: 'Keine Produkte',
    drinks_menu: 'Getränke Übersicht',
    ungrouped: 'Ohne Kategorie',
    cat_heiss: 'Heißgetränke',
    error_prefix: 'Fehler:',
    current_price: 'Aktueller Preis:',
  regular_price: 'Originalpreis:',
  saving: 'Ersparnis',
  more_expensive: 'Teurer um',
    info: 'Info',
    info_text: 'Einige Details zum Getränk können hier stehen.',
    history: 'Verlauf',
    history_text: 'Letzte Änderungen und Notizen.',
    user_dashboard: 'Benutzer-Dashboard',
    no_favorites: 'Noch keine Favoriten. Markiere ein Getränk mit dem Stern, um es hier anzuzeigen.',
    added: 'Hinzugefügt:',
    invalid_login: 'Ungültige Anmeldung',
    market_not_started: 'Der Markt ist noch nicht gestartet. Bitte warte, bis das Personal ihn aktiviert hat.',
    market_not_started_hint: 'Warum kann ich mich nicht anmelden?',
    table_name: 'Tischname',
    password: 'Passwort',
    session_not_found: 'Sitzung nicht gefunden.',
    table_not_found: 'Tisch nicht gefunden.',
    go_back: 'Zurück',
    currently_joined: 'Derzeit in Gruppe:',
    leave_party: 'Gruppe verlassen',
    not_in_party: 'Derzeit in keiner Gruppe',
    create_party_limit: 'Du kannst nur eine aktive Gruppe gleichzeitig haben. Schließe zuerst die bestehende Gruppe.',
    party_already_exists: 'Eine aktive Gruppe mit diesem Namen existiert bereits an diesem Tisch. Bitte schließe sie zuerst oder wähle einen anderen Namen.',
    creator_required: 'Fehlende Ersteller-ID. Bitte erneut versuchen.',
    enter_paid_amount: 'Bezahlt an der Kasse (Betrag eingeben):',
    paid_amount_invalid: 'Ungültiger Betrag.',
    paid_amount_mismatch: 'Bezahlt stimmt nicht mit dem Gruppenumsatz überein.',
  please_join_party: 'Bitte zuerst einer Gruppe auf deinem Tisch beitreten, um das Dashboard zu sehen.',
  go_to_party: 'Zu den Gruppen an deinem Tisch',
    table_label: 'an Tisch:',
    create_new_party: 'Neue Gruppe erstellen',
  enter_party_name: 'Gruppen-Name eingeben...',
  party_name: 'Gruppen Name',
    creating: 'Erstelle...',
    create_and_join: 'Erstellen & Beitreten',
  incorrect_password: 'Falsches Passwort',
  party_name_placeholder: 'z.B: Gruppe 1',
  party_name_placeholder_title: 'Gruppen Name',
  enter_party_password: 'Bitte Passwort für die Gruppe eingeben...',
  create_party_failed: 'Erstellen der Gruppe fehlgeschlagen',
  create_party: 'Gruppe erstellen',
    active_parties: 'Aktive Gruppen',
    no_parties: 'Noch keine Gruppen an diesem Tisch.',
    closed: 'Geschlossen',
    active: 'Aktiv',
    joined: 'Beigetreten',
    join: 'Beitreten',
    close: 'Schließen',
    parties_label: 'Gruppen',
    check_in: 'An einen Tisch setzen',
    check_out: 'Tisch verlassen',
    // Shopping basket
    shopping_basket: 'Warenkorb',
    no_orders_yet: 'Noch keine Bestellungen. Beginne Getränke zu bestellen!',
    total: 'Gesamt',
    trading_fee: 'Handelsgebühr (1%)',
    total_with_fee: 'Gesamt inkl. Gebühr',
    items: 'Artikel',
    basket_info: 'Bestellungen werden getrackt, aber noch nicht an Ready2Order übermittelt. Schließe deine Gruppen-Sitzung ab, um Bestellungen zu finalisieren.',
    add_to_basket: 'Zum Warenkorb hinzufügen',
    adding: 'Wird hinzugefügt...',
    order_added: 'Zum Warenkorb hinzugefügt!',
    order_failed: 'Fehler beim Hinzufügen zum Warenkorb',
    favorite_drinks: 'Lieblingsgetränke',
    cannot_leave_with_orders: 'Es gibt ausstehende oder finalisierte Bestellungen in dieser Gruppe. Bitte schließe oder lösche alle Bestellungen, bevor du die Gruppe verlässt.',
    creator_cannot_leave: 'Als Gruppenersteller kannst du die Gruppe nicht verlassen, solange es Bestellungen gibt. Bitte schließe die Gruppe oder übertrage die Inhaberschaft.',
    last_member_cannot_leave: 'Als letztes Mitglied kannst du die Gruppe nicht verlassen, solange es Bestellungen gibt. Bitte schließe die Gruppe zuerst.',
    must_leave_party_first: 'Bitte verlasse deine Gruppe, bevor du dich abmeldest.',
    only_creator_can_close: 'Nur der Ersteller der Gruppe kann diese wieder schließen.',
    creator_cannot_leave_last: 'Als Gruppenersteller und letztes Mitglied musst du die Gruppe schließen und alle Zahlungen abwickeln, bevor du gehen kannst.',
    cannot_close_with_finalized: 'Gruppe kann nicht geschlossen werden, solange finalisierte Bestellungen bestehen. Alle Zahlungen müssen an der Kasse beglichen werden.',
    error_closing_party: 'Fehler beim Schließen der Gruppe. Bitte versuche es erneut.',
    basket_timer_info: 'Artikel werden nach 1 Minute automatisch entfernt',
    remaining: 'verbleibend',
    continue_shopping: 'Weiter einkaufen',
    view_basket: 'Warenkorb ansehen',
    view_basket_items: 'Warenkorb-Artikel ansehen und verwalten',
    quantity: 'Menge',
    quantity_error: 'Bitte mindestens 1 Artikel auswählen',
    order_history: 'Bestellhistorie',
    drink: 'Getränk',
    party_password_placeholder: 'z.B: 1234',
    party_password_placeholder_title: 'Gruppen Passwort',
    ordered_price: 'Bestellpreis',
    savings_total: 'Gesamtersparnis',
    original_price: 'Originalpreis',
    no_history: 'Noch keine Bestellungen',
    in_basket: 'in deinem Warenkorb',
    finalize_order: 'Jetzt kostenpflichtig an der Bar bestellen!',
    finalizing: 'Wird abgeschickt...',
    order_finalized: 'Bestellung erfolgreich abgeschickt!',
    finalize_error: 'Fehler beim Abschicken der Bestellung',
    purchase_limit_exceeded: 'Bestelllimit erreicht',
    purchase_limit_message: 'Deine Gruppe ({members} Mitglieder) kann maximal {limit} Artikel im Warenkorb haben. Aktuell: {current}',
    // Admin Dashboard
    admin_dashboard: 'Admin-Dashboard',
    market_status: 'Markt-Status',
    market_started: 'Markt erfolgreich gestartet',
    market_stopped: 'Markt erfolgreich gestoppt',
    system_reset: 'System erfolgreich zurückgesetzt',
    failed_start_market: 'Fehler beim Starten des Markts',
    failed_stop_market: 'Fehler beim Stoppen des Markts',
    failed_reset_system: 'Fehler beim Zurücksetzen des Systems',
    running: 'Läuft',
    stopped: 'Gestoppt',
    reset: 'Zurückgesetzt',
    partially_reset: 'Teilweise zurückgesetzt',
    unknown: 'Unbekannt',
    danger_zone: 'Danger Zone',
    danger_zone_description: 'Diese Aktionen beeinflussen das gesamte System. Mit Vorsicht verwenden.',
    system_status: 'System-Status',
    regime: 'Regime',
    running_time: 'Laufzeit',
    tick_count: 'Tick-Anzahl',
    last_tick: 'Letzter Tick',
    system_clean_state: 'System ist in sauberer Zustand - keine Gruppen oder Bestellungen vorhanden',
    start_market: 'Markt starten',
    start_market_description: 'Initialisiere den Markt und aktiviere dynamische Preisberechnungen',
    starting: 'Wird gestartet...',
    stop_market: 'Markt stoppen',
    stop_market_description: 'Unterbreche alle Preisberechnungen ohne Daten zu löschen',
    stopping: 'Wird gestoppt...',
    reset_system: 'System zurücksetzen',
    reset_system_warning: '⚠️ WARNUNG: Dies löscht ALLE Gruppen, Bestellungen und verwandte Daten. Getränke werden auf Standardpreise zurückgesetzt. Diese Aktion kann NICHT rückgängig gemacht werden! Cleanup läuft im Hintergrund (30-60 Sekunden).',
    resetting: 'Wird zurückgesetzt...',
    confirm_reset: 'Ja, alles zurücksetzen',
    cancel: 'Abbrechen',
    reset_confirm_title: 'Bist du dir absolut sicher?',
    reset_confirm_subtitle: 'Dies löscht dauerhaft:',
    reset_delete_parties: 'Alle Gruppen (offen und geschlossen)',
    reset_delete_orders: 'Alle Bestellungen und Bestellpositionen',
    reset_delete_members: 'Alle Gruppenmitglieder',
    reset_delete_r2o: 'Alle R2O-Bestellungen und Produkte',
    reset_delete_snapshots: 'Alle Preis-Snapshots und Tick-Daten',
    reset_confirm_result: 'Der Markt wird gestoppt und Getränke auf Standardpreise zurückgesetzt.',
    parties: 'Gruppen',
    open: 'offen',
    orders: 'Bestellungen',
    finalized: 'abgeschlossen',
    pending: 'ausstehend',
    total_revenue: 'Gesamtumsatz',
    fees: 'Gebühren',
    drinks: 'Getränke',
    inactive: 'inaktiv',
    r2o_orders: 'R2O-Bestellungen',
    submitted: 'eingereicht',
    failed: 'fehlgeschlagen',
    active_members: 'Aktive Mitglieder',
    total_members: 'Gesamtmitglieder',
    top_drinks: 'Top 10 Getränke',
    sold: 'verkauft',
    never: 'Niemals',
    drinks_list: 'Getränkeliste',
    live_orders: 'Live-Bestellungen',
    live_orders_hint: 'Neueste 200 Bestellungen aller Tische',
    overview: 'Übersicht',
    days_short: 'Tg',
    house_is_winning: 'Das Haus gewinnt!!!',
    house_is_winning_menu: 'Das Haus gewinnt(?)',
    house_edge: 'Hausvorteil',
    house_gain_line: 'Vergleicht aktuellen Umsatz mit Normalpreisen inkl. 1% Gebühr',
    actual_revenue: 'Aktueller Umsatz',
    regular_revenue: 'Normalpreis-Umsatz',
    avg_order_value: 'Ø Bestellwert',
    orders_per_party: 'Bestellungen pro Gruppe',
    members: 'Mitglieder',
    no_members: 'Noch keine Mitglieder',
    price: 'Preis',
    status: 'Status',
    all_parties: 'Alle Gruppen',
    table: 'Tisch',
    tables: 'Tische',
    all_time_members: 'Mitglieder insgesamt',
    close_party: 'Gruppe schließen',
    closing: 'Wird geschlossen...',
    party_closed: 'Gruppe erfolgreich geschlossen',
    kick: 'Entfernen',
    member_kicked: 'Mitglied entfernt',
    error_kicking_member: 'Fehler beim Entfernen des Mitglieds',
    kick_member_help: 'Mitglieder können entfernt werden, wenn sie nicht zahlen oder gehen müssen.',
    close_party_help: 'Schließt die Gruppe sofort. Bestellungen bleiben bestehen.',
    event_banner_title: 'Campus Cneipe',
    event_banner_body: 'Beim Börsensaufen in der C2 wird der Getränkepreis zur echten Achterbahnfahrt 📈📉. Angelehnt an den Aktienhandel schwanken die Preise den ganzen Abend, abhängig von Angebot und Nachfrage. Gute Trades schlagen das Haus.',
    tick_frequency: 'Marktaktualisierung: alle 60 Sekunden',
    price_floor: 'Preisuntergrenze: Einkaufspreis',
    price_unlimited: 'Preisobergrenze: unbegrenzt',
    fair_play_notice: 'Fair Play: Offensichtlicher Missbrauch führt zu Normalpreisen und Ausschluss. Bei Fragen immer Personal ansprechen.',
    party_id_swap_notice: 'Party-Code nur gegen Studentenausweis; Ausweis gibt es nach Bezahlung zurück.',
    pay_at_register: 'Bezahlung erfolgt am Kassentresen nach dem Event.',
    event_rules_title: 'Event-Regeln',
    party_helper_title: 'Gruppenerstellung',
    party_helper_hint: 'Tauscht einen Ausweis gegen einen Party-Code, mit dem ihr teilnehmen könnt. Später könnt ihr die Bezahlung an der Kasse erledigen.',
    notification_broadcast_hint: 'Schicke eine kurze Nachricht an alle Nutzer gleichzeitig.',
    party_coc_title: 'Verhaltenskodex',
    event_countdown_title: 'Nächstes Mal Börsensaufen',
    event_countdown_cta: 'Bis dann – Wenn der Makrt wieder die C2 Regiert!',
    see_you_soon: 'Wir sehen uns zum Börsensaufen!',
    market_inactive_message: 'Der Markt ist aktuell gestoppt oder zurückgesetzt. Die App zeigt nur den Countdown.',
    notifications: 'Benachrichtigungen',
    message_required: 'Nachricht wird benötigt',
    notification_sent: 'Benachrichtigung verschickt',
    notification_failed: 'Senden der Benachrichtigung fehlgeschlagen',
    notification_placeholder: 'Was sollen alle sehen?',
    severity: 'Wichtigkeit',
    sending: 'Senden...',
    send: 'Senden',
    title: 'Titel',
    message: 'Nachricht',
    optional: 'Optional',
    success: 'Erfolg',
    warning: 'Warnung',
    danger: 'Gefahr',
    time: 'Zeit',
    dismiss: 'Schließen',
    quick_messages: 'Schnellnachrichten',
    category_market: 'Markt',
    category_safety: 'Sicherheit',
    category_bar: 'Bar & Service',
    category_kitchen: 'Küche',
    msg_market_started: 'Markt gestartet',
    msg_market_started_text: 'Der Getränkemarkt ist jetzt aktiv! Die Preise ändern sich dynamisch – jetzt geht es los!',
    msg_market_stopped: 'Markt gestoppt',
    msg_market_stopped_text: 'Der Getränkemarkt ist momentan nicht aktiv. Neue Bestellungen sind derzeit nicht möglich.',
    msg_event_ended: 'Event beendet',
    msg_event_ended_text: 'Das Event ist vorbei – keine weiteren Bestellungen möglich. Bitte bezahlt eure Rechnungen an der Kasse.',
    msg_safety_first: 'Sicherheit zuerst',
    msg_safety_first_text: 'Wenn du nicht sicher bist oder Hilfe brauchst, informiere sofort ein Mitglied des Personals.',
    msg_drink_water: 'Wasser trinken',
    msg_drink_water_text: 'Denk daran, ausreichend Wasser zu trinken! Hydration ist wichtig für deine Gesundheit und Sicherheit.',
    msg_long_queue: 'Lange Warteschlange',
    msg_long_queue_text: 'Es gibt eine lange Warteschlange an der Bar. Bitte haben Sie Geduld – wir arbeiten so schnell wie möglich.',
    msg_kitchen_open: 'Küche offen',
    msg_kitchen_open_text: 'Die Küche ist jetzt offen und nimmt Bestellungen an.',
    msg_kitchen_closed: 'Küche geschlossen',
    msg_kitchen_closed_text: 'Die Küche ist jetzt geschlossen. Es können keine neuen Essensbestellungen mehr aufgegeben werden.',
    msg_kitchen_closing_30: 'Küche schließt in 30 Minuten',
    msg_kitchen_closing_30_text: 'Die Küche schließt in 30 Minuten. Letzte Essensbestellungen sollten bald aufgegeben werden.',
    msg_kitchen_closing_15: 'Küche schließt in 15 Minuten',
    msg_kitchen_closing_15_text: 'Die Küche schließt in 15 Minuten. Dies ist die letzte Chance für Essensbestellungen!',
    end_event: 'Event beenden',
    end_event_description: 'Benachrichtigung senden, dass das Event beendet ist und keine weiteren Bestellungen möglich sind',
    ending: 'Beende...',
    bar_dashboard: 'Bar Dashboard',
    pending: 'Ausstehend',
    in_progress: 'In Bearbeitung',
    completed: 'Abgeschlossen',
    filter_orders: 'Bestellungen filtern',
    all: 'Alle',
    orders: 'Bestellungen',
    no_orders: 'Keine Bestellungen anzuzeigen',
    table: 'Tisch',
    party: 'Gruppe',
    ordered_at: 'Bestellt um',
    mark_pending: 'Als ausstehend markieren',
    start_work: 'Starten',
    mark_done: 'Fertig',
    new_orders: 'Neue Bestellungen',
    in_work: 'In Arbeit',
    finished: 'Fertig',
    archive: 'Archiv',
    show_archive: 'Archiv zeigen',
    hide_archive: 'Archiv ausblenden',
    avg_completion: 'Durchschn. Fertigstellungszeit',
    avg_wait: 'Durchschn. Wartezeit',
    avg_prep: 'Durchschn. Zubereitungszeit',
    influence: 'Einflussnahme',
    market_fee: 'Marktgebühr',
    pricing_config: 'Preis-Konfiguration',
    adjust_prices: 'Preise anpassen',
    capacity: 'Kapazität',
    priority: 'Priorität',
    hint_fee_decimal: 'Beispiel: 0,01 = 1%',
    save: 'Speichern',
  },
  en: {
    app_title: 'Stock Market Drinking 🍻',
    // categories
    cat_saefte: 'Juices & Spritzers',
    cat_bier: 'Beer & Beer Mixes',
    cat_non_alc: 'Softdrinks',
    cat_wine: 'Wine',
    cat_mocktails: 'Mocktails (alcohol free)',
    cat_cocktails: 'Cocktails',
    party_coc_title: 'Code of Conduct',
    home_title: 'Servus,',
    home_subtitle: 'Scan your table QR code to join the bar stock exchange!',
      finished_per_hour: 'Finished per Hour',
      disclaimer_title: 'Important Notice',
      disclaimer_1: 'No refunds possible',
      disclaimer_2: 'For security and management reasons, you can only place 3x your group size drinks into one order',
      disclaimer_3: 'All orders are delivered to the table at once, drinks cannot be delayed',
      disclaimer_4: 'Food is not included in the bar stock exchange',
      disclaimer_5: 'Ordering drinks at regular prices is not possible today',
      disclaimer_6: 'Opening a party can only be done in exchange for a student ID (or similar)',
      disclaimer_7: 'Each product has a hidden capacity, after that it\'s sold out for the night',
      disclaimer_8: 'There will be random events',
      disclaimer_9: 'Orders must be placed within 1 minute to keep the price',
    nav_home: 'Home',
    in_basket: 'in your basket',
    create_party: 'Create party',
    nav_drinks: 'Drinks',
    nav_dashboard: 'Dashboard',
    nav_my_party: 'My Party',
    login: 'Login',
    logout: 'Logout',
    notfound_title: '404 – Page Not Found',
    notfound_sub: "Sorry, we couldn't find the page you're looking for.",
    go_back_home: 'Go back home',
    cookie_prompt_title: 'Language & Cookies',
    cookie_prompt_text: 'Pick a language. We also store essential cookies (e.g. session). You can adjust others later.',
    accept: 'Accept',
    choose_de: 'Deutsch',
    choose_en: 'English',
  choose_language: 'Choose language',
    // additional
    loading: 'Loading...',
    no_products: 'No products',
    drinks_menu: 'Drinks Menu',
    ungrouped: 'Ungrouped',
    cat_heiss: 'Hot beverages',
    error_prefix: 'Error:',
    current_price: 'Current price:',
  regular_price: 'Original price:',
  saving: 'Saving',
  party_password_placeholder: 'e.g: 1234',
  party_password_placeholder_title: 'Party Password',
  enter_party_password: 'Please enter party password...',
  more_expensive: 'More expensive by',
    info: 'Info',
    info_text: 'Some details about the drink can go here.',
    history: 'History',
    history_text: 'Recent changes and notes.',
    user_dashboard: 'User Dashboard',
    no_favorites: 'No favorite drinks yet. Star a drink to add it here.',
    added: 'Added:',
    invalid_login: 'Invalid login',
    market_not_started: 'Market not started yet. Please wait until staff activates it.',
    market_not_started_hint: 'Why can\'t I log in?',
    table_name: 'Table name',
    password: 'Password',
    session_not_found: 'Session not found.',
    table_not_found: 'Table not found.',
    go_back: 'Go Back',
    currently_joined: 'Currently joined party:',
    leave_party: 'Leave Party',
    not_in_party: 'Not currently in any party',
    create_party_limit: 'You can only have one active party at a time. Close the current one first.',
    party_already_exists: 'An active party with this name already exists at this table. Please close it first or choose a different name.',
    creator_required: 'Missing creator id. Please try again.',
    enter_paid_amount: 'Enter amount paid at register:',
    paid_amount_invalid: 'Invalid amount.',
    paid_amount_mismatch: 'Paid amount does not match party spend.',
  please_join_party: 'Please join a party first, in order to view your dashboard.',
  go_to_party: 'View the parties at your table',
    table_label: 'at Table:',
    create_new_party: 'Create New Party',
  enter_party_name: 'Enter party name...',
  party_name: 'Party Name',
    creating: 'Creating...',
    create_and_join: 'Create & Join',
  incorrect_password: 'Incorrect password',
  party_name_placeholder: 'e.g: Group 1',
  party_name_placeholder_title: 'Party Name',
  create_party_failed: 'Failed to create party',
    active_parties: 'Active Parties',
    no_parties: 'No parties at this table yet.',
    closed: 'Closed',
    active: 'Active',
    joined: 'Joined',
    join: 'Join',
    close: 'Close',
    parties_label: 'Parties',
    check_in: 'Sit at a table',
    check_out: 'Leave table',
    // Shopping basket
    shopping_basket: 'Shopping Basket',
    no_orders_yet: 'No orders yet. Start ordering drinks!',
    total: 'Total',
    trading_fee: 'Trading Fee (1%)',
    total_with_fee: 'Total incl. Fee',
    items: 'items',
    basket_info: 'Orders are tracked but not yet submitted to Ready2Order. Complete your party session to finalize orders.',
    add_to_basket: 'Add to Basket',
    adding: 'Adding...',
    order_added: 'Added to basket!',
    order_failed: 'Failed to add to basket',
    favorite_drinks: 'Favorite Drinks',
    cannot_leave_with_orders: 'There are pending or finalized orders in this party. Please complete or clear all orders before leaving.',
    creator_cannot_leave: 'As the party creator, you cannot leave while there are orders. Please close the party or transfer ownership first.',
    last_member_cannot_leave: 'As the last member, you cannot leave while there are orders. Please close the party first.',
    must_leave_party_first: 'Please leave your party before logging out.',
    only_creator_can_close: 'Only the creator of the party can close it.',
    creator_cannot_leave_last: 'As the party creator and last member, you must close the party and settle all payments before leaving.',
    cannot_close_with_finalized: 'Cannot close party with finalized orders. All payments must be settled at the register before closing.',
    error_closing_party: 'Failed to close party. Please try again.',
    basket_timer_info: 'Items will be automatically removed after 1 minute',
    remaining: 'remaining',
    continue_shopping: 'Continue Shopping',
    view_basket: 'View Basket',
    view_basket_items: 'View and manage your basket items',
    quantity: 'Quantity',
    quantity_error: 'Please select at least 1 item',
    order_history: 'Order History',
    drink: 'Drink',
    ordered_price: 'Order Price',
    savings_total: 'Total Savings',
    original_price: 'Original Price',
    no_history: 'No orders yet',
    finalize_order: 'Order now at the bar (paid)!',
    finalizing: 'Submitting...',
    order_finalized: 'Order successfully submitted!',
    finalize_error: 'Error submitting order',
    purchase_limit_exceeded: 'Purchase limit exceeded',
    purchase_limit_message: 'Your party ({members} members) can have max {limit} pending items in basket. Currently: {current}',
    // Admin Dashboard
    admin_dashboard: 'Admin Dashboard',
    market_status: 'Market Status',
    market_started: 'Market started successfully',
    market_stopped: 'Market stopped successfully',
    system_reset: 'System reset successfully',
    failed_start_market: 'Failed to start market',
    failed_stop_market: 'Failed to stop market',
    failed_reset_system: 'Failed to reset system',
    running: 'Running',
    stopped: 'Stopped',
    reset: 'Reset',
    partially_reset: 'Partially Reset',
    unknown: 'Unknown',
    danger_zone: 'Danger Zone',
    danger_zone_description: 'These actions affect the entire system. Use with caution.',
    system_status: 'System Status',
    regime: 'Regime',
    running_time: 'Running Time',
    tick_count: 'Tick Count',
    last_tick: 'Last Tick',
    system_clean_state: 'System is in clean state - no parties or orders exist',
    start_market: 'Start Market',
    start_market_description: 'Initialize the market and enable dynamic pricing calculations',
    starting: 'Starting...',
    stop_market: 'Stop Market',
    stop_market_description: 'Pause all pricing calculations without deleting data',
    stopping: 'Stopping...',
    reset_system: 'Reset System',
    reset_system_warning: '⚠️ WARNING: This will delete ALL parties, orders, and related data. Drinks will be reset to default state. This action CANNOT be undone! Cleanup runs in background (30-60 seconds).',
    resetting: 'Resetting...',
    confirm_reset: 'Yes, Reset Everything',
    cancel: 'Cancel',
    reset_confirm_title: 'Are you absolutely sure?',
    reset_confirm_subtitle: 'This will permanently delete:',
    reset_delete_parties: 'All parties (open and closed)',
    reset_delete_orders: 'All orders and order items',
    reset_delete_members: 'All party members',
    reset_delete_r2o: 'All R2O orders and products',
    reset_delete_snapshots: 'All price snapshots and tick data',
    reset_confirm_result: 'Market will be stopped and drinks reset to default prices.',
    parties: 'Parties',
    open: 'open',
    orders: 'Orders',
    finalized: 'finalized',
    pending: 'pending',
    total_revenue: 'Total Revenue',
    fees: 'Fees',
    drinks: 'Drinks',
    inactive: 'inactive',
    r2o_orders: 'R2O Orders',
    submitted: 'submitted',
    failed: 'failed',
    active_members: 'Active Members',
    total_members: 'total members',
    top_drinks: 'Top 10 Drinks',
    sold: 'sold',
    never: 'Never',
    drinks_list: 'Drinks List',
    live_orders: 'Live Orders',
    live_orders_hint: 'Latest 200 orders across all tables',
    overview: 'Overview',
    days_short: 'd',
    house_is_winning: 'The House is fucking Winning!!!!',
    house_is_winning_menu: 'Das Haus gewinnt(?)',
    house_edge: 'House gain',
    house_gain_line: 'Comparing current revenue to regular pricing incl. 1% fee',
    influence: 'Influence',
    market_fee: 'Market Fee',
    pricing_config: 'Pricing Configuration',
    adjust_prices: 'Adjust Prices',
    capacity: 'Capacity',
    priority: 'Priority',
    hint_fee_decimal: 'Example: 0.01 = 1%',
    save: 'Save',
    actual_revenue: 'Actual revenue',
    regular_revenue: 'Regular revenue',
    avg_order_value: 'Avg order value',
    orders_per_party: 'Orders per party',
    members: 'Members',
    no_members: 'No members yet',
    price: 'Price',
    status: 'Status',
    all_parties: 'All Parties',
    table: 'Table',
    tables: 'Tables',
    all_time_members: 'All-time Members',
    close_party: 'Close Party',
    closing: 'Closing...',
    party_closed: 'Party closed successfully',
    kick: 'Kick',
    member_kicked: 'Member kicked',
    error_kicking_member: 'Failed to kick member',
    kick_member_help: 'Remove members who need to leave or haven’t settled.',
    close_party_help: 'Closes the party immediately. Orders remain for settlement.',
    event_banner_title: 'Campus Cneipe',
    event_banner_body: 'At C2 Stock Market Drinking, drink prices turn into a real rollercoaster 📈📉. Inspired by real stock trading, prices fluctuate all evening depending on supply and demand. Good trades can beat the house.',
    tick_frequency: 'Market update: every 60 seconds',
    price_floor: 'Price floor: buying cost',
    price_unlimited: 'Price ceiling: none',
    fair_play_notice: 'Fair play: obvious abuse → regular prices & exclusion. Talk to staff if unsure.',
    party_id_swap_notice: 'Party code only after swapping a student ID; ID returned after payment.',
    pay_at_register: 'Payment happens at the register after the event.',
    event_rules_title: 'Event rules',
    party_helper_title: 'Party creation',
    party_helper_hint: 'Swap an ID for your party code, keep it safe, and settle payment together at the register.',
    notification_broadcast_hint: 'Send a toast to every connected user instantly.',
    event_countdown_title: 'Next Börsensaufen session',
    event_countdown_cta: 'See you soon — when the market rules the C2 again!',
    see_you_soon: 'See you at Börsensaufen!',
    market_inactive_message: 'Market is currently stopped or reset. Only countdown is shown.',
    // Test mode notifications
    test_mode_enabled_message: 'Test Mode ENABLED - R2O calls will be skipped',
    test_mode_disabled_message: 'Test Mode DISABLED - R2O calls active',
    failed_toggle_test_mode: 'Failed to toggle test mode',
    notifications: 'Notifications',
    message_required: 'Message is required',
    notification_sent: 'Notification sent',
    notification_failed: 'Failed to send notification',
    notification_placeholder: 'What do you want to tell everyone?',
    severity: 'Severity',
    sending: 'Sending...',
    send: 'Send',
    title: 'Title',
    message: 'Message',
    optional: 'Optional',
    success: 'Success',
    warning: 'Warning',
    danger: 'Danger',
    time: 'Time',
    dismiss: 'Dismiss',
    quick_messages: 'Quick Messages',
    category_market: 'Market',
    category_safety: 'Safety',
    category_bar: 'Bar & Service',
    category_kitchen: 'Kitchen',
    msg_market_started: 'Market Started',
    msg_market_started_text: 'The drink market is now active! Prices change dynamically – let\'s go!',
    msg_market_stopped: 'Market Stopped',
    msg_market_stopped_text: 'The drink market is currently inactive. New orders are not possible right now.',
    msg_event_ended: 'Event Ended',
    msg_event_ended_text: 'The event has ended – no more orders are possible. Please settle your tabs at the register.',
    msg_safety_first: 'Safety First',
    msg_safety_first_text: 'If you\'re unsure or need help, please tell a staff member right away.',
    msg_drink_water: 'Drink Water',
    msg_drink_water_text: 'Remember to drink plenty of water! Hydration is important for your health and safety.',
    msg_long_queue: 'Long Queue',
    msg_long_queue_text: 'There is a long queue at the bar. Please be patient – we\'re working as fast as we can.',
    msg_kitchen_open: 'Kitchen Open',
    msg_kitchen_open_text: 'The kitchen is now open and taking orders.',
    msg_kitchen_closed: 'Kitchen Closed',
    msg_kitchen_closed_text: 'The kitchen is now closed. No new food orders can be placed.',
    msg_kitchen_closing_30: 'Kitchen Closing in 30 min',
    msg_kitchen_closing_30_text: 'The kitchen is closing in 30 minutes. Please place food orders soon.',
    msg_kitchen_closing_15: 'Kitchen Closing in 15 min',
    msg_kitchen_closing_15_text: 'The kitchen is closing in 15 minutes. This is the last chance for food orders!',
    end_event: 'End Event',
    end_event_description: 'Broadcast notification that the event has ended and no more orders are possible',
    ending: 'Ending...',
    bar_dashboard: 'Bar Dashboard',
    pending: 'Pending',
    in_progress: 'In Progress',
    completed: 'Completed',
    filter_orders: 'Filter Orders',
    all: 'All',
    orders: 'Orders',
    no_orders: 'No orders to display',
    table: 'Table',
    party: 'Party',
    ordered_at: 'Ordered at',
    mark_pending: 'Mark as Pending',
    start_work: 'Start Work',
    mark_done: 'Mark Done',
    new_orders: 'New Orders',
    in_work: 'In Work',
    finished: 'Finished',
    archive: 'Archive',
    show_archive: 'Show Archive',
    hide_archive: 'Hide Archive',
    avg_completion: 'Avg. Completion Time',
    avg_wait: 'Avg. Wait Time',
    avg_prep: 'Avg. Prep Time',
  },
}

const COOKIE_LANG = 'lang'
const COOKIE_CONSENT = 'cookie_consent'

function getCookie(name: string) {
  if (typeof document === 'undefined') return undefined
  const v = document.cookie.match('(^|;)\\s*' + name + '\\s*=\\s*([^;]+)')
  return v ? decodeURIComponent(v[2]) : undefined
}

function setCookie(name: string, value: string, days = 365) {
  if (typeof document === 'undefined') return
  const d = new Date()
  d.setTime(d.getTime() + days * 24 * 60 * 60 * 1000)
  document.cookie = `${name}=${encodeURIComponent(value)};path=/;expires=${d.toUTCString()}`
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('de')

  useEffect(() => {
    // Read existing cookies but do NOT write defaults here so the popup can ask the user.
    const c = getCookie(COOKIE_LANG)
    if (c === 'en' || c === 'de') {
      setLangState(c)
    } else {
      // default to de in memory only
      setLangState('de')
    }
  }, [])

  const setLang = (l: Lang) => {
    setLangState(l)
    setCookie(COOKIE_LANG, l)
  }

  const t = (key: string, fallback?: string) => {
    return TRANSLATIONS[lang][key] ?? fallback ?? key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}

// Helper to get both language versions of a key
export function getBothLanguages(key: string, fallback?: string): { de: string; en: string } {
  return {
    de: TRANSLATIONS.de[key] ?? fallback ?? key,
    en: TRANSLATIONS.en[key] ?? fallback ?? key,
  };
}

export { COOKIE_LANG, COOKIE_CONSENT }
